spring:
  application:
    name: activiti
  data:
    mongodb:
      host: ${mongo.connection.url}
      database: dms
  activiti:
    db-history-used: true
    history-level: audit
    deploymentMode: never-fail
    check-process-definitions: false
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/activiti?&serverTimezone=Asia/Shanghai
  redis:
    database: 0
    host: ${redis.ip}
    port: ${redis.port}
    password:
    # 连接超时时间（毫秒）
    timeout: 9999
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 1
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
mybatis:
  mapper-locations: classpath*:mapper/*.xml

server:
  port: 8001
  servlet:
    context-path:
feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
